services:
  - type: web
    name: qoneqt-ai-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: APP_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_ENDPOINT_URL
        sync: false
